import { ThemePreset, ModuleDefinition } from './wizardTypes';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'mode',
    name: 'Mode & Prêt-à-porter',
    badge: 'Tendance',
    icon: '👗',
    description: 'Design épuré et minimaliste chic, typographie soignée, idéal pour vêtements, maroquinerie et accessoires de mode.',
    colors: {
      bg: '#FFFFFF',
      secondary: '#F8F9FA',
      text: '#0F172A',
      accent: '#B48B57',
    },
    sampleTagline: 'Collections exclusives & Prêt-à-porter artisanal',
    sampleProducts: [
      {
        name: 'Robe en lin naturel',
        price: 89.0,
        category: 'Vêtements',
        image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Sac cabas cuir surpiqué',
        price: 145.0,
        category: 'Maroquinerie',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Veste structurée sable',
        price: 120.0,
        category: 'Vestes',
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'pizza',
    name: 'Restauration & Pizzeria',
    badge: 'Restauration',
    icon: '🍕',
    description: 'Ambiance feutrée dark mode, accents rouge braise, parfaitement adapté pour commande à table & Click & Collect.',
    colors: {
      bg: '#141414',
      secondary: '#1E2026',
      text: '#FAF9F6',
      accent: '#E63946',
    },
    sampleTagline: 'Pizzas artisanales au feu de bois & Recettes napolitaines',
    sampleProducts: [
      {
        name: 'Pizza Regina Truffe',
        price: 16.5,
        category: 'Pizzas',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Burrata Crémeuse Pugliese',
        price: 12.0,
        category: 'Antipasti',
        image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910a451?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Tiramisu traditionnel',
        price: 7.5,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'burger',
    name: 'Street Food & Burgers',
    badge: 'Gourmet',
    icon: '🍔',
    description: 'Style contemporain dynamique, accents dorés/ambrés, mettant en valeur les formules repas et la livraison.',
    colors: {
      bg: '#121212',
      secondary: '#1C1C1C',
      text: '#F5F5F5',
      accent: '#FFB703',
    },
    sampleTagline: 'Burgers gourmets, frites maison & Sauces signatures',
    sampleProducts: [
      {
        name: 'Le Bacon Smash Supreme',
        price: 14.9,
        category: 'Burgers',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Frites fraîches Cheddar Truffe',
        price: 5.5,
        category: 'Sides',
        image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Cookie géant chocolat pécan',
        price: 4.5,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'green',
    name: 'Artisanat, Bio & Nature',
    badge: 'Éco-conçu',
    icon: '🌿',
    description: 'Teintes douces sauge et lin, univers apaisant pour cosmétiques bio, herboristeries, créations éco-responsables.',
    colors: {
      bg: '#F4F6F0',
      secondary: '#EAEDE4',
      text: '#1F3322',
      accent: '#588157',
    },
    sampleTagline: 'Soins naturels & Créations faites main en circuit court',
    sampleProducts: [
      {
        name: 'Savon surgras Calendula Bio',
        price: 7.9,
        category: 'Cosmétique',
        image: 'https://images.unsplash.com/photo-1607006314041-945fa403ef88?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Bougie cire de soja & Verveine',
        price: 19.0,
        category: 'Maison',
        image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Infusion bio Nuit Paisible',
        price: 9.5,
        category: 'Herboristerie',
        image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'jewelry',
    name: 'Bijouterie & Luxe',
    badge: 'Prestige',
    icon: '💎',
    description: 'Noir profond, typographie serif prestigieuse, touches d\'or fin pour sublimer pièces d\'exception et créations d\'orfèvre.',
    colors: {
      bg: '#0D0D0D',
      secondary: '#1A1A1A',
      text: '#F8F8F8',
      accent: '#D4AF37',
    },
    sampleTagline: 'Haute joaillerie & Créations orfèvres sur-mesure',
    sampleProducts: [
      {
        name: 'Bague solitaire Or blanc & Diamant',
        price: 490.0,
        category: 'Bagues',
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Collier pendentif Émeraude sertie',
        price: 320.0,
        category: 'Colliers',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Montre chronographe automatique',
        price: 850.0,
        category: 'Horlogerie',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
  {
    id: 'classic',
    name: 'Boutique Universelle / Vitrine',
    badge: 'Polyvalent',
    icon: '✨',
    description: 'Style élégant intemporel, fond crème doux et or artisanal, idéal pour artisans d\'art, créateurs et commerces de quartier.',
    colors: {
      bg: '#FAF9F6',
      secondary: '#FAF8F5',
      text: '#1A1A1A',
      accent: '#D5C295',
    },
    sampleTagline: 'Savoir-faire artisanal & Sélection d’excellence',
    sampleProducts: [
      {
        name: 'Coffret dégustation artisanal',
        price: 35.0,
        category: 'Épicerie fine',
        image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Céramique tournée à la main',
        price: 28.0,
        category: 'Art de la table',
        image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80',
      },
      {
        name: 'Carnet relié cuir véritable',
        price: 22.0,
        category: 'Papeterie',
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
];

export const MODULES_CATALOG: ModuleDefinition[] = [
  {
    code: 'site_web',
    name: 'Site Vitrine & Catalogue',
    icon: '🌐',
    stepName: 'Socle Essentiel',
    monthlyPrice: 15.0,
    yearlyPrice: 144.0, // 12€/mois
    description: 'Page d\'accueil personnalisée, présentation, formulaire de contact, SEO optimisé et médiathèque.',
    features: ['Nom de domaine & SSL inclus', 'Éditeur visuel de thème', 'Formulaire de contact & SEO', 'Médiathèque illimitée'],
    isBase: true,
  },
  {
    code: 'ecommerce',
    name: 'Boutique E-Commerce & Stocks',
    icon: '🛍️',
    stepName: 'Vente & Encaissement',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0, // 24€/mois
    description: 'Vente en ligne, gestion des stocks, variantes, base clients, factures légales et encaissement CB sécurisé inclus.',
    features: ['Catalogue produits & variantes', 'Panier d\'achat & tunnel de vente', 'Paiements CB WoxxPay/Stripe inclus', 'Facturation légale & TVA FEC incluses'],
  },
  {
    code: 'woxxship',
    name: 'Livraisons WoxxShip',
    icon: '🚚',
    stepName: 'Logistique & Expéditions',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0,
    description: 'Génération automatique d\'étiquettes et bordereaux d\'expédition Colissimo et Mondial Relay avec suivi en direct.',
    features: ['Génération bordereaux Colissimo/Relay', 'Tarifs négociés transporteurs', 'Numéros de suivi automatisés', 'Notifications d\'expédition clients'],
    requiredModule: 'ecommerce',
  },
  {
    code: 'click_and_collect',
    name: 'Click & Collect / Table',
    icon: '📦',
    stepName: 'Retrait Express',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0,
    description: 'Retrait rapide en boutique avec choix de créneau horaire de retrait ou commande directement à table.',
    features: ['Créneaux horaires de retrait', 'Commande au comptoir & table', 'Gestion des flux aux heures de pointe', 'Notification SMS/Email de commande prête'],
    requiredModule: 'ecommerce',
  },
  {
    code: 'reservations',
    name: 'Prise de Rendez-vous',
    icon: '📅',
    stepName: 'Agenda & Planning',
    monthlyPrice: 25.0,
    yearlyPrice: 240.0,
    description: 'Calendrier interactif et prise de rendez-vous en ligne directement rattachée à vos prestations de catalogue.',
    features: ['Calendrier hebdomadaire/journalier', 'Capacités et durées par créneau', 'Confirmation instantanée client', 'Rappels automatiques'],
  },
  {
    code: 'analytics',
    name: 'Statistiques & CA Avancés',
    icon: '📊',
    stepName: 'Pilotage & Croissance',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0,
    description: 'Tableaux de bord d\'analyse des ventes, panier moyen, produits phares et audit de conversion client.',
    features: ['Chiffre d\'affaires en temps réel', 'Analyse du panier moyen', 'Top ventes & taux de transformation', 'Rapports comptables exportables'],
    requiredModule: 'ecommerce',
  },
  {
    code: 'notifications',
    name: 'Alertes Smartphone Telegram',
    icon: '🔔',
    stepName: 'Notifications',
    monthlyPrice: 10.0,
    yearlyPrice: 96.0,
    description: 'Notification instantanée sur votre smartphone via Telegram à chaque nouvelle commande ou réservation passée.',
    features: ['Alertes push instantanées Telegram', 'Détail commande & montant en 1 seconde', 'Routage emails transactionnels SMTP', 'Alertes rupture de stock'],
  },
  {
    code: 'loyalty_coupons',
    name: 'Fidélité & Codes Promo',
    icon: '🎁',
    stepName: 'Fidélisation',
    monthlyPrice: 10.0,
    yearlyPrice: 96.0,
    description: 'Création de codes promotionnels, réductions en pourcentage ou euros fixes, et cartes cadeaux dématérialisées.',
    features: ['Codes promo illimités (%, €)', 'Dates de validité & minima d\'achat', 'Génération de cartes cadeaux', 'Statistiques d\'utilisation'],
    requiredModule: 'ecommerce',
  },
];
