import { ThemePreset, ModuleDefinition } from './wizardTypes';

export const THEME_PRESETS: ThemePreset[] = [
  // 🍽️ 1. RESTAURATION & ALIMENTATION
  {
    id: 'boulangerie',
    name: 'Boulangerie & Pâtisserie',
    category: 'food',
    badge: 'Artisanal',
    icon: '🥖',
    description: 'Pains au levain, viennoiseries dorées, gâteaux signatures et formules déjeuner.',
    colors: { bg: '#FCFBF7', secondary: '#F5EFEB', text: '#2B1E16', accent: '#D49A58' },
    sampleTagline: 'Pains au levain naturel & Pâtisseries fines du jour',
    sampleProducts: [
      { name: 'Pain de campagne au levain', price: 4.2, category: 'Pains', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80' },
      { name: 'Croissant pur beurre AOP', price: 1.6, category: 'Viennoiseries', image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80' },
      { name: 'Tartelette framboises fraîches', price: 5.5, category: 'Pâtisseries', image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop&q=80' },
      { name: 'Baguette Tradition croustillante', price: 1.3, category: 'Pains', image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'pizza',
    name: 'Pizzeria & Restauration',
    category: 'food',
    badge: 'Restauration',
    icon: '🍕',
    description: 'Ambiance feutrée dark mode, accents rouge braise, parfait pour Click & Collect et commande à table.',
    colors: { bg: '#141414', secondary: '#1E2026', text: '#FAF9F6', accent: '#E63946' },
    sampleTagline: 'Pizzas artisanales au feu de bois & Recettes napolitaines',
    sampleProducts: [
      { name: 'Pizza Regina Truffe', price: 16.5, category: 'Pizzas', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80' },
      { name: 'Burrata Crémeuse Pugliese', price: 12.0, category: 'Antipasti', image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910a451?w=600&auto=format&fit=crop&q=80' },
      { name: 'Tiramisu traditionnel café', price: 7.5, category: 'Desserts', image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80' },
      { name: 'Pizza Diavola Spianata Piccante', price: 15.0, category: 'Pizzas', image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'burger',
    name: 'Street Food & Burgers',
    category: 'food',
    badge: 'Street Food',
    icon: '🍔',
    description: 'Style contemporain dynamique, accents dorés/ambrés, idéal pour les formules et le retrait rapide.',
    colors: { bg: '#121212', secondary: '#1C1C1C', text: '#F5F5F5', accent: '#FFB703' },
    sampleTagline: 'Burgers gourmets, frites fraîches & Sauces signatures',
    sampleProducts: [
      { name: 'Le Bacon Smash Supreme', price: 14.9, category: 'Burgers', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80' },
      { name: 'Frites fraîches Cheddar Truffe', price: 5.5, category: 'Sides', image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80' },
      { name: 'Cookie géant chocolat pécan', price: 4.5, category: 'Desserts', image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80' },
      { name: 'Crispy Chicken & Avocat', price: 13.9, category: 'Burgers', image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'caviste',
    name: 'Caviste & Vins Fins',
    category: 'food',
    badge: 'Grands Crus',
    icon: '🍷',
    description: 'Vins d\'auteurs, champagnes de vignerons, spiritueux d\'exception et coffrets cadeaux.',
    colors: { bg: '#171214', secondary: '#231C20', text: '#F8F5F6', accent: '#9E2A2B' },
    sampleTagline: 'Vins de vignerons indépendants & Spiritueux rares',
    sampleProducts: [
      { name: 'Bourgogne Pinot Noir 2022', price: 28.0, category: 'Rouge', image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80' },
      { name: 'Champagne Brut Grand Cru', price: 48.0, category: 'Bulles', image: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?w=600&auto=format&fit=crop&q=80' },
      { name: 'Sancerre Blanc Minéral 2023', price: 24.5, category: 'Blanc', image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=600&auto=format&fit=crop&q=80' },
      { name: 'Coffret Dégustation 3 Bouteilles', price: 75.0, category: 'Coffrets', image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'coffee',
    name: 'Café & Torréfaction',
    category: 'food',
    badge: 'Specialty Coffee',
    icon: '☕',
    description: 'Grains d\'origine pure, thés rares, machines expresso et accessoires baristas.',
    colors: { bg: '#FDFBF7', secondary: '#F4ECE4', text: '#342621', accent: '#B07D62' },
    sampleTagline: 'Cafés de spécialité fraîchement torréfiés & Thés d\'exception',
    sampleProducts: [
      { name: 'Éthiopie Yirgacheffe Grains 250g', price: 11.5, category: 'Cafés', image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=80' },
      { name: 'Matcha Cérémonial Bio Japon', price: 24.0, category: 'Thés', image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80' },
      { name: 'Cafetière à piston cuivre', price: 39.0, category: 'Accessoires', image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80' },
      { name: 'Cold Brew artisanal bouteille 50cl', price: 4.9, category: 'Boissons', image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'chocolatier',
    name: 'Chocolatier & Confiserie',
    category: 'food',
    badge: 'Gourmandise',
    icon: '🍫',
    description: 'Pralinés pur beurre de cacao, ganaches d\'origine et confiseries artisanales.',
    colors: { bg: '#1A1412', secondary: '#281F1C', text: '#FAF5F2', accent: '#C89666' },
    sampleTagline: 'Chocolats fins d\'exception & Confiseries faites main',
    sampleProducts: [
      { name: 'Coffret Pralinés & Ganaches 24 pièces', price: 32.0, category: 'Coffrets', image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80' },
      { name: 'Tablette Madagascar 72% Criollo', price: 6.8, category: 'Tablettes', image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&auto=format&fit=crop&q=80' },
      { name: 'Amandes enrobées cacao poudré', price: 12.5, category: 'Grignotages', image: 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=600&auto=format&fit=crop&q=80' },
      { name: 'Pâte à tartiner noisettes du Piémont', price: 9.5, category: 'Tartinables', image: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?w=600&auto=format&fit=crop&q=80' },
    ],
  },

  // 👗 2. MODE, ACCESSOIRES & LUXE
  {
    id: 'mode',
    name: 'Mode & Prêt-à-porter',
    category: 'fashion',
    badge: 'Tendance',
    icon: '👗',
    description: 'Design épuré et minimaliste chic, idéal pour vêtements, maroquinerie et collections capsules.',
    colors: { bg: '#FFFFFF', secondary: '#F8F9FA', text: '#0F172A', accent: '#B48B57' },
    sampleTagline: 'Collections exclusives & Prêt-à-porter artisanal',
    sampleProducts: [
      { name: 'Robe en lin naturel', price: 89.0, category: 'Vêtements', image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&auto=format&fit=crop&q=80' },
      { name: 'Sac cabas cuir surpiqué', price: 145.0, category: 'Maroquinerie', image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80' },
      { name: 'Veste structurée sable', price: 120.0, category: 'Vestes', image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80' },
      { name: 'Ceinture cuir boucle laiton', price: 45.0, category: 'Accessoires', image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'jewelry',
    name: 'Bijouterie & Joaillerie',
    category: 'fashion',
    badge: 'Prestige',
    icon: '💎',
    description: 'Noir profond, typographie serif prestigieuse, touches d\'or fin pour sublimer pièces et gemmes.',
    colors: { bg: '#0D0D0D', secondary: '#1A1A1A', text: '#F8F8F8', accent: '#D4AF37' },
    sampleTagline: 'Haute joaillerie & Créations orfèvres sur-mesure',
    sampleProducts: [
      { name: 'Bague solitaire Or blanc & Diamant', price: 490.0, category: 'Bagues', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80' },
      { name: 'Collier pendentif Émeraude sertie', price: 320.0, category: 'Colliers', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80' },
      { name: 'Montre chronographe automatique', price: 850.0, category: 'Horlogerie', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80' },
      { name: 'Boucles d\'oreilles perles de culture', price: 195.0, category: 'Boucles', image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'sneakers',
    name: 'Sneakers & Streetwear',
    category: 'fashion',
    badge: 'Street Culture',
    icon: '👟',
    description: 'Paires limitées, streetwear premium, hoodies oversize et accessoires urbains.',
    colors: { bg: '#0B0D12', secondary: '#161B22', text: '#FFFFFF', accent: '#00F0FF' },
    sampleTagline: 'Éditions limitées & Streetwear contemporain',
    sampleProducts: [
      { name: 'Sneakers Retro High OG', price: 180.0, category: 'Sneakers', image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&auto=format&fit=crop&q=80' },
      { name: 'Hoodie Boxy Fit 450g Noir', price: 85.0, category: 'Vêtements', image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80' },
      { name: 'Casquette 5-Panel brodée', price: 35.0, category: 'Accessoires', image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80' },
      { name: 'Chaussettes techniques côtelées', price: 16.0, category: 'Accessoires', image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&auto=format&fit=crop&q=80' },
    ],
  },

  // 🌿 3. BEAUTÉ, BIEN-ÊTRE & SOINS
  {
    id: 'green',
    name: 'Cosmétique Bio & Savons',
    category: 'beauty',
    badge: 'Éco-responsable',
    icon: '🌿',
    description: 'Soins naturels, savons saponifiés à froid, huiles végétales et bien-être éco-conçu.',
    colors: { bg: '#F4F6F0', secondary: '#EAEDE4', text: '#1F3322', accent: '#588157' },
    sampleTagline: 'Soins naturels & Créations faites main en circuit court',
    sampleProducts: [
      { name: 'Savon surgras Calendula Bio', price: 7.9, category: 'Savons', image: 'https://images.unsplash.com/photo-1607006314041-945fa403ef88?w=600&auto=format&fit=crop&q=80' },
      { name: 'Huile de jojoba pure première pression', price: 18.5, category: 'Soins visage', image: 'https://images.unsplash.com/photo-1608248597359-21669c3a3721?w=600&auto=format&fit=crop&q=80' },
      { name: 'Baume réparateur karité & lavande', price: 14.0, category: 'Soins corps', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80' },
      { name: 'Gommage corps marc de café & amande', price: 16.9, category: 'Gommages', image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'spa_beaute',
    name: 'Institut de Beauté & Spa',
    category: 'beauty',
    badge: 'Soins & Spa',
    icon: '💆',
    description: 'Réservation de massages, soins visage haute technologie, rituels bien-être et cartes cadeaux.',
    colors: { bg: '#FAF6F4', secondary: '#F3EAE5', text: '#3E2A24', accent: '#C48B71' },
    sampleTagline: 'Rituels de soins holistiques & Parenthèse de sérénité',
    sampleProducts: [
      { name: 'Rituel Massage Signature 60 min', price: 85.0, category: 'Massages', image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&auto=format&fit=crop&q=80' },
      { name: 'Soin du visage Éclat & Hydratation', price: 70.0, category: 'Visage', image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80' },
      { name: 'Accès Espace Hammam & Jacuzzi', price: 45.0, category: 'Détente', image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80' },
      { name: 'Coffret Cadeau Soin Prestige', price: 120.0, category: 'Cadeaux', image: 'https://images.unsplash.com/photo-1512290900672-1f5be1ebdf1c?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'coiffure',
    name: 'Coiffure & Barbier',
    category: 'services',
    badge: 'Rendez-vous',
    icon: '💇',
    description: 'Prise de rendez-vous en ligne, coupes homme/femme, taille de barbe et produits capillaires pro.',
    colors: { bg: '#16181B', secondary: '#212529', text: '#F8F9FA', accent: '#D4A373' },
    sampleTagline: 'Salon de coiffure & Barbier traditionnel sur rendez-vous',
    sampleProducts: [
      { name: 'Coupe Homme & Taille de Barbe au coupe-chou', price: 42.0, category: 'Barbier', image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&auto=format&fit=crop&q=80' },
      { name: 'Balayage Signature & Soin Gloss', price: 110.0, category: 'Femme', image: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?w=600&auto=format&fit=crop&q=80' },
      { name: 'Huile à barbe nourrissante bois de cèdre', price: 22.0, category: 'Soins', image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&auto=format&fit=crop&q=80' },
      { name: 'Cire coiffante mate fixation forte', price: 19.5, category: 'Coiffants', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80' },
    ],
  },

  // 🏡 4. MAISON, ARTISANAT & FLEURS
  {
    id: 'fleuriste',
    name: 'Fleuriste & Végétal',
    category: 'craft',
    badge: 'Nature & Fleurs',
    icon: '🌸',
    description: 'Bouquets de saison, fleurs séchées, compositions de mariage et plantes vertes en pot.',
    colors: { bg: '#FCFAF7', secondary: '#F2ECE4', text: '#2D312E', accent: '#C86D51' },
    sampleTagline: 'Créations florales poétiques & Végétaux de saison',
    sampleProducts: [
      { name: 'Bouquet de saison Pastel & Pivoines', price: 38.0, category: 'Bouquets', image: 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=600&auto=format&fit=crop&q=80' },
      { name: 'Cloche de fleurs séchées éternelles', price: 45.0, category: 'Fleurs séchées', image: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&auto=format&fit=crop&q=80' },
      { name: 'Monstera Deliciosa en pot terre cuite', price: 29.0, category: 'Plantes', image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600&auto=format&fit=crop&q=80' },
      { name: 'Couronne murale eucalyptus & immortelles', price: 34.0, category: 'Décoration', image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'deco_maison',
    name: 'Maison, Déco & Céramique',
    category: 'craft',
    badge: 'Art de Vivre',
    icon: '🛋️',
    description: 'Céramiques tournées main, linge de maison en lin lavé, luminaires et objets d\'artisanat.',
    colors: { bg: '#F8F6F0', secondary: '#EFECE2', text: '#2B2823', accent: '#C97A56' },
    sampleTagline: 'Objets décoratifs uniques & Artisanat de la maison',
    sampleProducts: [
      { name: 'Vase sculptural grès chamotté', price: 58.0, category: 'Céramique', image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80' },
      { name: 'Plaid lin lavé gaufré terracotta', price: 79.0, category: 'Textile', image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80' },
      { name: 'Lampe à poser opaline & laiton', price: 110.0, category: 'Luminaires', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80' },
      { name: 'Bougie végétale parfum Bois de Cèdre', price: 24.0, category: 'Maison', image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'librairie',
    name: 'Librairie & Papeterie',
    category: 'craft',
    badge: 'Culture & Papier',
    icon: '📚',
    description: 'Coups de cœur littéraires, beaux livres d\'art, carnets reliés et stylos plumes de collection.',
    colors: { bg: '#FAF8F3', secondary: '#EFE8DC', text: '#241D18', accent: '#3D5A80' },
    sampleTagline: 'Sélection littéraire indépendante & Papeterie de création',
    sampleProducts: [
      { name: 'Beau Livre d\'Art Photographique', price: 42.0, category: 'Beaux Livres', image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80' },
      { name: 'Carnet cuir artisanal papier coton', price: 26.0, category: 'Papeterie', image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop&q=80' },
      { name: 'Stylo plume corps ébonite & plume dorée', price: 65.0, category: 'Écriture', image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80' },
      { name: 'Marque-pages en laiton gravé', price: 8.5, category: 'Accessoires', image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'animaux',
    name: 'Animalerie & Accessoires',
    category: 'craft',
    badge: 'Animaux',
    icon: '🐾',
    description: 'Alimentation naturelle bio, colliers cuir sur-mesure, jouets éco-conçus et paniers douillets.',
    colors: { bg: '#FBF9F5', secondary: '#F1ECE2', text: '#2C2520', accent: '#E07A5F' },
    sampleTagline: 'Produits sains & Accessoires confortables pour vos compagnons',
    sampleProducts: [
      { name: 'Collier cuir tannage végétal gravé', price: 34.0, category: 'Colliers', image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&auto=format&fit=crop&q=80' },
      { name: 'Coussin orthopédique velours lavable', price: 68.0, category: 'Couchage', image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=600&auto=format&fit=crop&q=80' },
      { name: 'Friandises naturelles canard & herbes', price: 7.9, category: 'Friandises', image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&auto=format&fit=crop&q=80' },
      { name: 'Jouet corde coton bio robuste', price: 9.5, category: 'Jouets', image: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?w=600&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'classic',
    name: 'Boutique Universelle / Vitrine',
    category: 'general',
    badge: 'Polyvalent',
    icon: '✨',
    description: 'Style élégant intemporel, fond crème doux et or artisanal, adapté à tout commerce de proximité et artisans.',
    colors: { bg: '#FAF9F6', secondary: '#FAF8F5', text: '#1A1A1A', accent: '#D5C295' },
    sampleTagline: 'Savoir-faire artisanal & Sélection d’excellence',
    sampleProducts: [
      { name: 'Coffret dégustation artisanal', price: 35.0, category: 'Épicerie fine', image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80' },
      { name: 'Céramique tournée à la main', price: 28.0, category: 'Art de la table', image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80' },
      { name: 'Carnet relié cuir véritable', price: 22.0, category: 'Papeterie', image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80' },
      { name: 'Savon parfumé végétal', price: 8.0, category: 'Soins', image: 'https://images.unsplash.com/photo-1607006314041-945fa403ef88?w=600&auto=format&fit=crop&q=80' },
    ],
  },
];

export const MODULES_CATALOG: ModuleDefinition[] = [
  {
    code: 'site_web',
    name: 'Site Vitrine & Catalogue',
    icon: '🌐',
    stepName: 'Socle Essentiel',
    monthlyPrice: 15.0,
    yearlyPrice: 144.0, // 12€/mois
    description: 'Page d\'accueil personnalisée, présentation, formulaire de contact, SEO optimisé et médiathèque.',
    features: ['Nom de domaine & SSL inclus', 'Éditeur visuel de thème', 'Formulaire de contact & SEO', 'Médiathèque illimitée'],
    isBase: true,
  },
  {
    code: 'ecommerce',
    name: 'Boutique E-Commerce & Stocks',
    icon: '🛍️',
    stepName: 'Vente & Encaissement',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0, // 24€/mois
    description: 'Vente en ligne, gestion des stocks, variantes, base clients, factures légales et encaissement CB sécurisé inclus.',
    features: ['Catalogue produits & variantes', 'Panier d\'achat & tunnel de vente', 'Paiements CB WoxxPay/Stripe inclus', 'Facturation légale & TVA FEC incluses'],
  },
  {
    code: 'woxxship',
    name: 'Livraisons WoxxShip',
    icon: '🚚',
    stepName: 'Logistique & Expéditions',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0,
    description: 'Génération automatique d\'étiquettes et bordereaux d\'expédition Colissimo et Mondial Relay avec suivi en direct.',
    features: ['Génération bordereaux Colissimo/Relay', 'Tarifs négociés transporteurs', 'Numéros de suivi automatisés', 'Notifications d\'expédition clients'],
    requiredModule: 'ecommerce',
  },
  {
    code: 'click_and_collect',
    name: 'Click & Collect / Table',
    icon: '📦',
    stepName: 'Retrait Express',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0,
    description: 'Retrait rapide en boutique avec choix de créneau horaire de retrait ou commande directement à table.',
    features: ['Créneaux horaires de retrait', 'Commande au comptoir & table', 'Gestion des flux aux heures de pointe', 'Notification SMS/Email de commande prête'],
    requiredModule: 'ecommerce',
  },
  {
    code: 'reservations',
    name: 'Prise de Rendez-vous',
    icon: '📅',
    stepName: 'Agenda & Planning',
    monthlyPrice: 25.0,
    yearlyPrice: 240.0,
    description: 'Calendrier interactif et prise de rendez-vous en ligne directement rattachée à vos prestations de catalogue.',
    features: ['Calendrier hebdomadaire/journalier', 'Capacités et durées par créneau', 'Confirmation instantanée client', 'Rappels automatiques'],
  },
  {
    code: 'analytics',
    name: 'Statistiques & CA Avancés',
    icon: '📊',
    stepName: 'Pilotage & Croissance',
    monthlyPrice: 30.0,
    yearlyPrice: 288.0,
    description: 'Tableaux de bord d\'analyse des ventes, panier moyen, produits phares et audit de conversion client.',
    features: ['Chiffre d\'affaires en temps réel', 'Analyse du panier moyen', 'Top ventes & taux de transformation', 'Rapports comptables exportables'],
    requiredModule: 'ecommerce',
  },
  {
    code: 'notifications',
    name: 'Alertes Smartphone Telegram',
    icon: '🔔',
    stepName: 'Notifications',
    monthlyPrice: 10.0,
    yearlyPrice: 96.0,
    description: 'Notification instantanée sur votre smartphone via Telegram à chaque nouvelle commande ou réservation passée.',
    features: ['Alertes push instantanées Telegram', 'Détail commande & montant en 1 seconde', 'Routage emails transactionnels SMTP', 'Alertes rupture de stock'],
  },
  {
    code: 'loyalty_coupons',
    name: 'Fidélité & Codes Promo',
    icon: '🎁',
    stepName: 'Fidélisation',
    monthlyPrice: 10.0,
    yearlyPrice: 96.0,
    description: 'Création de codes promotionnels, réductions en pourcentage ou euros fixes, et cartes cadeaux dématérialisées.',
    features: ['Codes promo illimités (%, €)', 'Dates de validité & minima d\'achat', 'Génération de cartes cadeaux', 'Statistiques d\'utilisation'],
    requiredModule: 'ecommerce',
  },
];
